name: Semantic Release for Apps

on:
  push:
    branches:
      - master
    # paths:
    #   - 'modules/**'
  workflow_run:
    workflows: ["My Workflow"]
    types:
      - completed  
  
permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB2 }}

      # Step 1: Get the name of the folder that had the changes
      - name: Get changed directories
        id: changed_dirs
        run: |
          CHANGED_DIRS=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ 'BEGIN{OFS=FS} NF--')
          if [[ -z $CHANGED_DIRS ]]; then
            echo "::set-output name=dirs::"
          else
            echo "::set-output name=dirs::$CHANGED_DIRS"
          fi