name: Get Changed File

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB2 }}

      # Ensure your semantic release steps or any other necessary steps are here

      - name: Get Changed Files
        run: |
          git fetch origin master
          CHANGED_FILES=$(git diff --name-only origin/master)
          echo "Changed files in the merge commit:"
          echo "$CHANGED_FILES" > changed_files.txt

      - name: Display Changed Files
        run: cat changed_files.txt
